version: 0.2

phases:
  install:
    runtime-versions: 
      nodejs: 10
  pre_build:
    commands:
    - echo Installing npm dependencies...
    - npm install
  build:
    commands:
      - echo Starting build...
      - npm run build
  post_build:
    commands:
      - echo Build completed on this 'date'...
artifacts:
  paths:
    - './build/**/*'
   

